### ISSUE TITLE
why does +39 return vatican instead of italy

### ISSUE THREAD

**Issue by emmaxCreative** [bottlepay/flutter_libphonenumber#5]
when entering an italian number it returns "vatikanstadt" instead of italy as detected country.

Is this the expected behaviour or how can I get Italy as the country of origin ?

**Comment by acoutts** [comment]
It's impossible to accurately derive the country name from the phone code. The reason is many countries share the same country code at the beginning and have the same phone pattern. That's why it's best to always display a dropdown list for the user to pick their country if it's important to know the correct country.

**Comment by emmaxCreative** [comment]
alright thanks for the info.
