### ISSUE TITLE
Austrian Phone number missing 1 digit

### ISSUE THREAD

**Issue by emmaxCreative** [bottlepay/flutter_libphonenumber#6]
when entering an austrian mobile number there is one digit missing. 

for example the number is 664 1234567
but the inputformatter stops at 664 123456

I think it is the same problem as in #4 with a different country

**Comment by emmaxCreative** [comment]
@bottlepay can you please check this... We really need this feature in production but because we have lots of austrian users it is not possible if the number cant be fully inserted..

**Comment by acoutts** [comment]
Similar to #4, it seems to be working as expected as long as you specify `National` and `Mobile` for the `phoneNumberFormat` and `phoneNumberType`:

Before formatting:
<img width="389" alt="Screen Shot 2020-10-25 at 11 32 03 AM" src="https://user-images.githubusercontent.com/9597207/97111540-b797c280-16b5-11eb-9564-02999a577135.png">

After formatting (sync):
<img width="452" alt="Screen Shot 2020-10-25 at 11 32 29 AM" src="https://user-images.githubusercontent.com/9597207/97111544-c4b4b180-16b5-11eb-8c3f-25e94b8d5bc0.png">

**Comment by acoutts** [comment]
@emmaxCreative  moving here to keep organized:
>@acoutts the problem is not that the number is not marked as valid but that the LibPhonenumberTextFormatter stops the textfield from entering the last number.

>Whenever I parse the number +43 664 1234100 it returns it as valid number
But when I try to enter this number in a textfield with the inputFormatter set then the last digit cant be typed because the input is limited. So my guess is that the lenght limit is wrong ? I know it is a mobile number and i use the mobile mask for it.

I've just tested and when set to mobile / national, the as you type formatter does not truncate it either:
<img width="447" alt="Screen Shot 2020-10-25 at 11 36 56 AM" src="https://user-images.githubusercontent.com/9597207/97111646-63411280-16b6-11eb-9d68-9f5b672913f8.png">

Make sure you're setting `phoneNumberType` and `phoneNumberFormat` on the input formatter and it should work as expected. If I omit those settings on the input formatter then it indeed behaves as you reported.

**Comment by emmaxCreative** [comment]
Thank you! With `PhoneNumberType.national` it works as you described.

**Comment by acoutts** [comment]
Woohoo! Great to hear.

**Comment by yaroslav-kahaniak** [comment]
Hey @acoutts ,
First, thank you for maintaining this package.

I face the same issue - the `formatNumberSync` function truncates the full Austrian phone number. Changing the `phoneNumberFormat` passed to the function fixes this issue, but messes up the formatting of other international phone numbers. Example:
* UA phone numbers format changes from XX XXX XXXX to XXX XXX XXX
* formatter doesn’t truncate UA phone numbers the same way it did when `phoneNumberFormat` was set to `international`, allowing the input of a leading 0 in the phone number body, which shouldn't be allowed.
